Mapping_and_Transformation/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api_call.urls')),
    path('html/form/', include('html_form.urls')),
    path('', include('file_upload.urls')),    
]

api_call/urls.py
from django.urls import path
from api_call import views

app_name = "api_call"
urlpatterns = [
    path('call',views.create_turtle_script, name='upload_file')
]

file_upload/urls.py
from django.urls import path
from file_upload import views

app_name = "file_upload"
urlpatterns = [
    path('',views.upload_file, name='upload_file')
]

html_form/urls.py
from django.urls import path
from html_form import views

app_name = "html_form"
urlpatterns = [
    path('',views.create_turtle_script, name='create'),
]

html_form/models.py
from django.db import models

# Create your models here.

api_call/views.py
import json
from django.shortcuts import render
from django.http import JsonResponse
from rest_framework.decorators import api_view
from Mapping_and_Transformation.utilities import transformation_matrix

# Create your views here.

@api_view(['POST'])
def create_turtle_script(request):
    if request.method == "POST":
        turtle_list = []
        results = json.loads(request.body)

        for result_dict in results:
            firstname = result_dict["firstname"]
            lastname = result_dict["lastname"]
            birthdate = result_dict["birthdate"]
            mailingstreet = result_dict["mailingstreet"]
            mailingcity = result_dict["mailingcity"]
            mailingstate = result_dict["mailingstate"]
            mailingcountry = result_dict["mailingcountry"]
            mailingpostcode = result_dict["mailingpostcode"]
            email = result_dict["email"]
            mobilephonenumber = result_dict["mobilephonenumber"]
            homephonenumber = result_dict["homephonenumber"]
            employeetitle = result_dict["employeetitle"]
            employername = result_dict["employername"]
            employerindustry = result_dict["employerindustry"]
            employerstreet = result_dict["employerstreet"]
            employercity = result_dict["employercity"]
            employerstate = result_dict["employerstate"]
            employerpostcode = result_dict["employerpostcode"]
            employercountry = result_dict["employercountry"]
            employeremail = result_dict["employeremail"]
            employerphone = result_dict["employerphone"]
            employerfax = result_dict["employerfax"]

            row_list = [firstname, lastname, birthdate, mailingstreet, mailingcity, mailingstate, 
                            mailingcountry, mailingpostcode, email, mobilephonenumber, homephonenumber, 
                            employeetitle, employername, employerindustry, employerstreet, employercity, 
                            employerstate, employerpostcode, employercountry, employeremail, employerphone, employerfax, ]            
            turtle_list.append(row_list)

        turtle_str = transformation_matrix(turtle_list)
    
    return JsonResponse({"Turtle": turtle_str})

file_upload/views.py
import csv
from io import TextIOWrapper
from django.shortcuts import render
from Mapping_and_Transformation.utilities import transformation_matrix

# Create your views here.
def upload_file(request):
    if request.method == 'POST':
        myFile = request.FILES["myFile"]
        if myFile.name.endswith('.csv'):
            turtle_list = []
            csv_file = TextIOWrapper(myFile.file, encoding='utf-8')            
            csv_reader = csv.reader(csv_file)
            next(csv_reader)

            for row in csv_reader:
                firstname = row[0]
                lastname = row[1]
                birthdate = row[2]
                mailingstreet = row[3]
                mailingcity = row[4]
                mailingstate = row[5]
                mailingcountry = row[6]
                mailingpostcode = row[7]
                email = row[8]
                mobilephonenumber = row[8]
                homephonenumber = row[9]
                employeetitle = row[10]
                employername = row[11]
                employerindustry = row[12]
                employerstreet = row[13]
                employercity = row[14]
                employerstate = row[15]
                employerpostcode = row[16]
                employercountry = row[17]
                employeremail = row[18]
                employerphone = row[19]
                employerfax = row[20]

                row_list = [firstname, lastname, birthdate, mailingstreet, mailingcity, mailingstate, 
                            mailingcountry, mailingpostcode, email, mobilephonenumber, homephonenumber, 
                            employeetitle, employername, employerindustry, employerstreet, employercity, 
                            employerstate, employerpostcode, employercountry, employeremail, employerphone, employerfax, ]            
                turtle_list.append(row_list)
            turtle_str = transformation_matrix(turtle_list)

            context = { "turtle": turtle_str}

        return render(request, 'file_upload/upload_file.html', context)
    else:
        return render(request, 'file_upload/upload_file.html')

html_form/views.py
from django.shortcuts import render
from Mapping_and_Transformation.utilities import transformation_form_matrix

# Create your views here.
def create_turtle_script(request):
    if request.method == "GET":
        return render(request, 'html_form/index.html')
    else:
        firstname = request.POST.get("firstname", "")
        lastname = request.POST.get("lastname", "")
        birthdate = request.POST.get("birthdate", "")
        mailingstreet = request.POST.get("mailingstreet", "")
        mailingcity = request.POST.get("mailingcity", "")
        mailingstate = request.POST.get("mailingstate", "")
        mailingcountry = request.POST.get("mailingcountry", "")
        mailingpostcode = request.POST.get("mailingpostcode", "")
        email = request.POST.get("email", "")
        mobilephonenumber = request.POST.get("mobilephonenumber", "")
        homephonenumber = request.POST.get("homephonenumber", "")
        employeetitle = request.POST.get("employeetitle", "")
        employername = request.POST.get("employername", "")
        employerindustry = request.POST.get("employerindustry", "")
        employerstreet = request.POST.get("employerstreet", "")
        employercity = request.POST.get("employercity", "")
        employerstate = request.POST.get("employerstate", "")
        employerpostcode = request.POST.get("employerpostcode", "")
        employercountry = request.POST.get("employercountry", "")
        employeremail = request.POST.get("employeremail", "")
        employerphone = request.POST.get("employerphone", "")
        employerfax = request.POST.get("employerfax", "")

        row_list = [firstname, lastname, birthdate, mailingstreet, mailingcity, mailingstate, 
                    mailingcountry, mailingpostcode, email, mobilephonenumber, homephonenumber, 
                    employeetitle, employername, employerindustry, employerstreet, employercity, 
                    employerstate, employerpostcode, employercountry, employeremail, employerphone, employerfax, ]
        turtle_str = transformation_form_matrix(row_list)

        # print(f"Row List --> {row_list}")

        context = { "turtle": turtle_str}
        return render(request, 'html_form/view.html', context)

file_upload/templates/file_upload/upload_file.html
{% extends 'base_file.html' %}
{%  block content %}
{% load static %}
    <div class="container">
        <form method="POST" action="{% url 'file_upload:upload_file' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <label for="formFile" class="form-label">Default file input example</label>
                <input class="form-control" name="myFile" type="file" id="formFile">
            </div>
            <div class="col-3">
                <button type="submit" class="btn btn-success my-2" data-dismiss="modal"> <i class='uil-file-upload-alt'></i>  Upload Template </button>
            </div>
        </form>

        <div class="col-md-12">
            {{turtle|linebreaksbr}}
        </div>
    </div>
{%  endblock %}

html_form/templates/html_form/index.html
{% extends 'base_file.html' %}
{%  block content %}
{% load static %}
    <div class="container">
        <form method="POST" action="{% url 'html_form:create' %}">
            {% csrf_token %}
            <div class="row" style="padding-top: 2%;">
                <div class="col-md-3">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="firstname" placeholder="Enter first name">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="mailingcity" placeholder="Enter mailing city">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="email" placeholder="Enter email">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employername" placeholder="Enter employer name">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employerstate" placeholder="Enter employer state">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employerphone" placeholder="Enter employer phone">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="lastname" placeholder="Enter last name">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="mailingstate" placeholder="Enter mailing state">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="mobilephonenumber" placeholder="Enter mobile phone number">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employerindustry" placeholder="Enter employer industry">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employerpostcode" placeholder="Enter employer postcode">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employerfax" placeholder="Enter employer fax">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="col-md-12">
                        <input type="date" class="form-control" name="birthdate" placeholder="Enter birth date">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="mailingcountry" placeholder="Enter mailing country">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="homephonenumber" placeholder="Enter home phone number">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employerstreet" placeholder="Enter employer street">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employercountry" placeholder="Enter employer country">
                    </div>
                </div>

                <div class="col-md-3">
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="mailingstreet" placeholder="Enter mailing street">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="mailingpostcode" placeholder="Enter mailing post code">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employeetitle" placeholder="Enter employee title">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employercity" placeholder="Enter employer city">
                    </div>
                    <br>
                    <div class="col-md-12">
                        <input type="text" class="form-control" name="employeremail" placeholder="Enter employer email">
                    </div>
                </div>
            </div>

            <div class="row" style="padding-top: 2%;">
                <div class="col-md-12">
                    <input type="submit" class="btn btn-success mb-3" value="Submit">
                </div>
            </div>
        </form>
    </div>
{%  endblock %}

html_form/templates/html_form/view.html
{% extends 'base_file.html' %}
{%  block content %}
{% load static %}
<div class="container">
    <div class="col-md-12">
        {{turtle|linebreaksbr}}
    </div>
</div>
{%  endblock %}

templates/base_file.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <title>Source Form</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #333333;">
        <div class="container-fluid">
          <a class="navbar-brand" >Mapping The Gatekeepers</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'file_upload:upload_file' %}">File Upload</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'html_form:create' %}">Form Data</a>
              </li>              
            </ul>
           
          </div>
        </div>
      </nav>
    {% block content%} {% endblock%}
</body>
</html>